"""initial_schema

Revision ID: 4c5436a0d0f1
Revises: 
Create Date: 2026-06-19 23:34:30.971229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5436a0d0f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('upload', 'gdrive', name='source_type_enum'), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('source_local_path', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
    sa.Column('default_prompt', sa.Text(), nullable=False),
    sa.Column('default_reference_image_urls', sa.JSON(), nullable=True),
    sa.Column('resolution', sa.Enum('480p', '720p', '1080p', name='resolution_enum'), nullable=False),
    sa.Column('gdrive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('created', 'analyzing', 'review', 'queued', 'processing', 'stitching', 'delivering', 'done', 'failed', name='job_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_local_path', sa.Text(), nullable=True),
    sa.Column('result_gdrive_file_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('has_face', sa.Boolean(), nullable=False),
    sa.Column('action', sa.Enum('swap', 'keep', name='segment_action_enum'), nullable=False),
    sa.Column('prompt_override', sa.Text(), nullable=True),
    sa.Column('reference_image_urls_override', sa.JSON(), nullable=True),
    sa.Column('pre_roll_sec', sa.Float(), nullable=False),
    sa.Column('post_roll_sec', sa.Float(), nullable=False),
    sa.Column('kie_upload_url', sa.Text(), nullable=True),
    sa.Column('seedance_task_id', sa.String(length=255), nullable=True),
    sa.Column('seedance_result_url', sa.Text(), nullable=True),
    sa.Column('local_clip_path', sa.Text(), nullable=True),
    sa.Column('local_result_path', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'uploading', 'submitted', 'generating', 'completed', 'failed', 'skipped', name='segment_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_job_id'), 'segments', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segments_job_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_table('jobs')
    # ### end Alembic commands ###
