"""add_v2_project_runs_schema

Revision ID: 81b441a0932d
Revises: 4c5436a0d0f1
Create Date: 2026-06-20 04:05:15.569201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b441a0932d'
down_revision: Union[str, None] = '4c5436a0d0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('upload', 'gdrive', name='project_source_type_enum'), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('source_local_path', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('created', 'analyzing', 'ready', 'failed', name='project_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('reference_image_urls', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.Enum('480p', '720p', '1080p', name='run_resolution_enum'), nullable=False),
    sa.Column('gdrive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('created', 'queued', 'processing', 'stitching', 'delivering', 'done', 'failed', name='run_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_local_path', sa.Text(), nullable=True),
    sa.Column('result_gdrive_file_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_table('segment_defs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=False),
    sa.Column('end_sec', sa.Float(), nullable=False),
    sa.Column('has_face', sa.Boolean(), nullable=False),
    sa.Column('action', sa.Enum('swap', 'keep', name='segment_def_action_enum'), nullable=False),
    sa.Column('pre_roll_sec', sa.Float(), nullable=False),
    sa.Column('post_roll_sec', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segment_defs_project_id'), 'segment_defs', ['project_id'], unique=False)
    op.create_table('run_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('segment_def_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'uploading', 'submitted', 'generating', 'completed', 'failed', 'skipped', name='run_segment_status_enum'), nullable=False),
    sa.Column('kie_upload_url', sa.Text(), nullable=True),
    sa.Column('seedance_task_id', sa.String(length=255), nullable=True),
    sa.Column('seedance_result_url', sa.Text(), nullable=True),
    sa.Column('local_clip_path', sa.Text(), nullable=True),
    sa.Column('local_result_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_def_id'], ['segment_defs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_segments_run_id'), 'run_segments', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_segments_run_id'), table_name='run_segments')
    op.drop_table('run_segments')
    op.drop_index(op.f('ix_segment_defs_project_id'), table_name='segment_defs')
    op.drop_table('segment_defs')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('video_projects')
    # ### end Alembic commands ###
