"""
AI model registry — the per-model capability table for swap generation.

A ``Run.model`` value names one entry here. Everything that varies between the
generation backends lives in this module: the kie.ai model id, which
resolutions are offered, how long a clip may be, how the output duration is
derived, and whether the model exposes an explicit audio switch.

Why a registry: before this module the same five facts about each model were
restated in eight places (the ``run_model_enum``, ``_SEEDANCE_KIE_MODEL`` in
pipeline_v2, ``_VALID_MODELS`` + ``_MODEL_RESOLUTIONS`` in api_v2,
``_MODEL_LABELS`` in web_v2, the New Run ``<select>``, a ``MODEL_RESOLUTIONS``
JS map, and a ternary in run_detail.html). Adding a model meant finding all
eight. Now they all read from here, and the template layer gets the JS maps
serialised from :func:`resolution_choices_json` / :func:`model_limits_json`.

Keep this module free of app imports so api_v2, web_v2, kie_client and
pipeline_v2 can all depend on it, and treat it as the single source of truth for
the enum's valid values (mirrored by the ``run_model_enum`` Postgres type — see
migrations e5a1c7d2f3b6, b4f6d8e0c357 and c8d2f4a6e971).

Note the v1 pipeline (``app/pipeline.py``) still carries its own Seedance/Omni
constants. It is frozen and single-model, so it is deliberately left alone; only
the v2 path reads this registry.

Adding a model
--------------
1. Add an :class:`AIModelSpec` to :data:`AI_MODELS`.
2. Add the key to ``run_model_enum`` with an ``ALTER TYPE ... ADD VALUE``
   migration (Postgres enum values can never be removed — pick the name once).
That is the whole change; every v2 call site is driven off this table.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class AIModelSpec:
    """Capabilities of one generation backend."""

    # Value stored in runs.model (the run_model_enum label).
    key: str
    # Human-readable name, shown wherever a run's model is displayed.
    label: str
    # kie.ai createTask "model" field. Seedance variants share one request
    # schema and differ only by this id; Gemini Omni has its own payload shape
    # (see KieClient.create_omni_task) and is flagged by `family`.
    kie_model_id: str
    # Which request builder the pipeline must use: "seedance" | "omni".
    family: str
    # Resolutions offered in the UI and accepted by the API, in display order.
    # A run asking for one that is absent is coerced by resolution_or_default,
    # which picks the closest supported tier rather than a positional entry.
    resolutions: tuple[str, ...]
    # Hard ceiling (seconds) on BOTH the reference clip we upload and the
    # output duration we request. Drives segmentation caps and submit-time
    # trimming — a swap segment longer than this cannot be generated by this
    # model, so it is marked failed at submit time with RunSegment
    # .source_fallback set. Because that failure is deterministic — no number of
    # retries makes the segment generatable on this model — the completeness gate
    # lets the run through and the stitch substitutes the ORIGINAL footage for
    # that segment. The run completes and delivers, but part of the video is
    # un-swapped, which the run UI and Run.source_fallback_segments both flag.
    # (Transient failures still block the run; see _skip_segment.)
    max_clip_sec: float
    # Shortest reference clip the model will accept. Swap clips are padded up to
    # this before upload (see _submit_swap_segment_isolated). Seedance 2.0
    # rejects clips under ~1.8s; Seedance 2.5 in video-editing mode requires
    # 4-30s and rejects the whole request below that.
    min_clip_sec: float
    # True when the model derives the output's aspect ratio AND duration from the
    # input video rather than from the request, and REJECTS the request unless we
    # say so explicitly: aspect_ratio must be "adaptive" and duration must be -1.
    #
    # Seedance 2.5 does this whenever it classifies the task as video editing,
    # which it does from the prompt — and every swap submission we make is video
    # editing ("replace the character in the reference video", with a reference
    # video attached), so for 2.5 this is always on. Sending a concrete ratio or
    # duration instead earns:
    #   500 ... `ratio` must be `adaptive`. `duration` must be -1.
    #
    # This is strictly better for us than the alternative: the output then has
    # exactly the input clip's length instead of a rounded whole-second duration,
    # so the per-segment drift the old clamp introduced (a 7.4s clip asking for
    # 7s of output) disappears. Nothing downstream trims the result — clips are
    # concatenated whole — so matching the input exactly is what the stitch wants.
    follows_input_geometry: bool
    # Output-duration bounds sent in the createTask payload. Ignored when
    # follows_input_geometry is set (the duration is -1, not a length).
    min_duration_sec: int
    max_duration_sec: int
    # When set, the model accepts only these exact output durations and the
    # clip length is snapped to the nearest one (Gemini Omni). When None the
    # duration is clamped into [min_duration_sec, max_duration_sec].
    allowed_durations: Optional[tuple[int, ...]]
    # True when createTask accepts a `generate_audio` boolean. Models without it
    # write audio (or not) on their own and reject the field outright.
    supports_generate_audio: bool
    # True when the model produces an audio track at all. Gemini Omni never
    # does, so its runs are forced to audio_mode="original".
    produces_audio: bool
    # One-line description shown next to the model in the New Run form.
    hint: str


# Aspect ratios accepted by the Seedance family.
SEEDANCE_ASPECTS = frozenset({"1:1", "4:3", "16:9", "9:16", "21:9", "adaptive"})

# Every resolution label any model offers, cheapest/smallest first. Needed
# because "which resolution is closest to the one asked for" is an ordering
# question and AIModelSpec.resolutions is a *display* order — the two agree
# today, and resolution_or_default must not depend on them continuing to.
_RESOLUTION_ORDER: tuple[str, ...] = ("480p", "720p", "1080p", "4k")
_RESOLUTION_RANK: dict[str, int] = {r: i for i, r in enumerate(_RESOLUTION_ORDER)}


def _resolution_rank(resolution: str) -> int:
    """Sort key for a resolution label; unknown labels sort lowest.

    A label missing from _RESOLUTION_ORDER means a model was added without
    extending it. Sorting it below everything keeps the fallback conservative
    (cheapest) instead of accidentally promoting it to "highest supported".
    """
    return _RESOLUTION_RANK.get(resolution, -1)


AI_MODELS: dict[str, AIModelSpec] = {
    "seedance": AIModelSpec(
        key="seedance",
        label="Seedance 2.0",
        kie_model_id="bytedance/seedance-2",
        family="seedance",
        resolutions=("480p", "720p", "1080p"),
        max_clip_sec=15.0,
        min_clip_sec=2.0,
        follows_input_geometry=False,
        min_duration_sec=4,
        max_duration_sec=15,
        allowed_durations=None,
        supports_generate_audio=False,
        produces_audio=True,
        hint="video-to-video character swap",
    ),
    "seedance-fast": AIModelSpec(
        key="seedance-fast",
        label="Seedance 2.0 Fast",
        kie_model_id="bytedance/seedance-2-fast",
        family="seedance",
        resolutions=("480p", "720p"),
        max_clip_sec=15.0,
        min_clip_sec=2.0,
        follows_input_geometry=False,
        min_duration_sec=4,
        max_duration_sec=15,
        allowed_durations=None,
        supports_generate_audio=False,
        produces_audio=True,
        hint="faster, cheaper character swap",
    ),
    "seedance-mini": AIModelSpec(
        key="seedance-mini",
        label="Seedance 2.0 Mini",
        kie_model_id="bytedance/seedance-2-mini",
        family="seedance",
        resolutions=("480p", "720p"),
        max_clip_sec=15.0,
        min_clip_sec=2.0,
        follows_input_geometry=False,
        min_duration_sec=4,
        max_duration_sec=15,
        allowed_durations=None,
        supports_generate_audio=False,
        produces_audio=True,
        hint="lightweight character swap",
    ),
    "seedance-2-5": AIModelSpec(
        key="seedance-2-5",
        label="Seedance 2.5",
        kie_model_id="bytedance/seedance-2-5",
        family="seedance",
        # 2.5 tops out at 720p — it cannot stand in for base Seedance at 1080p.
        resolutions=("480p", "720p"),
        # The headline gain over 2.0: 30s per clip instead of 15s, so a project
        # can be cut into far fewer, longer segments (fewer stitch seams, less
        # identity drift across cuts). Requires the project to opt into a
        # matching segmentation cap — see VideoProject.max_segment_sec.
        max_clip_sec=30.0,
        min_clip_sec=4.0,
        follows_input_geometry=True,
        # Unused while follows_input_geometry is set (the duration sent is -1),
        # but kept honest so validate_duration still describes the model if that
        # ever changes.
        min_duration_sec=4,
        max_duration_sec=30,
        allowed_durations=None,
        supports_generate_audio=True,
        produces_audio=True,
        hint="longest clips (30s) and an explicit audio switch",
    ),
    "gemini-omni": AIModelSpec(
        key="gemini-omni",
        label="Gemini Omni",
        kie_model_id="gemini-omni-video",
        family="omni",
        resolutions=("720p", "1080p", "4k"),
        max_clip_sec=10.0,
        min_clip_sec=2.0,
        follows_input_geometry=False,
        min_duration_sec=4,
        max_duration_sec=10,
        allowed_durations=(4, 6, 8, 10),
        supports_generate_audio=False,
        produces_audio=False,
        hint="multimodal video generation",
    ),
}

DEFAULT_MODEL = "seedance"
VALID_MODELS = frozenset(AI_MODELS)

# Smallest max_clip_sec across every model. A project segmented at this cap can
# be run on ANY model without a segment being skipped — the historical default,
# and what VideoProject.max_segment_sec=NULL falls back to.
UNIVERSAL_MAX_SEGMENT_SEC = min(s.max_clip_sec for s in AI_MODELS.values())

# Largest max_clip_sec across every model — the ceiling the project setting and
# its API validation accept.
ABSOLUTE_MAX_SEGMENT_SEC = max(s.max_clip_sec for s in AI_MODELS.values())


def spec_for(model: Optional[str]) -> AIModelSpec:
    """Return the spec for *model*, falling back to the default backend.

    The fallback keeps callers safe against a NULL/unknown value on a row that
    predates a model being added.
    """
    return AI_MODELS.get(model or "", AI_MODELS[DEFAULT_MODEL])


def label_for(model: Optional[str]) -> str:
    """Human-readable label for a model key (used by templates)."""
    return AI_MODELS[model].label if model in AI_MODELS else (model or "")


def kie_model_id(model: Optional[str]) -> str:
    """kie.ai createTask model id for *model*."""
    return spec_for(model).kie_model_id


def is_omni(model: Optional[str]) -> bool:
    """True when *model* uses the Gemini Omni request shape."""
    return spec_for(model).family == "omni"


def resolutions_for(model: Optional[str]) -> tuple[str, ...]:
    """Allowed resolutions for *model*, in display order."""
    return spec_for(model).resolutions


def resolution_or_default(model: Optional[str], resolution: Optional[str]) -> str:
    """Return *resolution* if this model supports it, else the closest tier.

    This is the guard for "the run asks for something this backend cannot do"
    (e.g. a 1080p run submitted to Seedance 2.5, which stops at 720p):

    * exact match → pass it straight through;
    * otherwise the HIGHEST supported tier that does not exceed the request —
      the closest thing to what was asked for without over-spending;
    * otherwise (the request is below everything this model offers, or is
      NULL/unrecognised) the model's LOWEST tier. There is no non-exceeding
      candidate, so the minimum upgrade is the only defensible pick — jumping
      to the model's top tier would turn a stray value into a 4k bill on
      Gemini Omni, whose cheapest option is 720p.

    Ranked via :data:`_RESOLUTION_RANK`, not by tuple position: display order
    happens to be ascending today, and a positional ``resolutions[0]`` would
    silently downgrade a 1080p production run to Seedance 2.5's 480p.
    """
    spec = spec_for(model)
    if resolution in spec.resolutions:
        return resolution  # type: ignore[return-value]
    ranked = sorted(spec.resolutions, key=_resolution_rank)
    want = _RESOLUTION_RANK.get(resolution or "")
    if want is not None:
        not_exceeding = [r for r in ranked if _resolution_rank(r) <= want]
        if not_exceeding:
            return not_exceeding[-1]
    return ranked[0]


def max_clip_sec(model: Optional[str]) -> float:
    """Hard per-clip ceiling (seconds) for *model*."""
    return spec_for(model).max_clip_sec


def min_clip_sec(model: Optional[str]) -> float:
    """Shortest reference clip *model* accepts; swap clips are padded up to it."""
    return spec_for(model).min_clip_sec


# Sentinel duration meaning "match the input video". Not a length — do not clamp
# or compare it against min/max_duration_sec.
FOLLOW_INPUT_DURATION = -1


def duration_for(model: Optional[str], start: float, end: float) -> int:
    """Derive the output duration to request for a clip.

    Three behaviours, by model:
      * ``follows_input_geometry`` (Seedance 2.5) → :data:`FOLLOW_INPUT_DURATION`
        (-1). The model takes the output length from the input video and rejects
        any concrete value; this is also more accurate than we could be, since
        the output then matches the clip exactly instead of a rounded second.
      * fixed duration set (Gemini Omni) → snapped to the nearest allowed value.
      * otherwise → rounded and clamped into the model's supported range.
    """
    spec = spec_for(model)
    if spec.follows_input_geometry:
        return FOLLOW_INPUT_DURATION
    raw = end - start
    if spec.allowed_durations:
        return min(spec.allowed_durations, key=lambda d: abs(d - raw))
    return max(spec.min_duration_sec, min(spec.max_duration_sec, int(round(raw))))


def aspect_for(model: Optional[str], raw: Optional[str]) -> str:
    """Aspect ratio to send for *model*, given the source's ratio *raw*.

    A model that takes its geometry from the input video requires the literal
    ``"adaptive"`` and rejects anything else — including a ratio that happens to
    match the source. Everything else passes *raw* through when Seedance accepts
    it, falling back to ``"adaptive"``.
    """
    if spec_for(model).follows_input_geometry:
        return "adaptive"
    return raw if raw in SEEDANCE_ASPECTS else "adaptive"


def validate_duration(model: Optional[str], duration: int) -> None:
    """Raise ``ValueError`` if *duration* is not requestable for *model*."""
    spec = spec_for(model)
    if spec.follows_input_geometry:
        # -1 is the only legal value: the model derives length from the input.
        if duration != FOLLOW_INPUT_DURATION:
            raise ValueError(
                f"duration must be {FOLLOW_INPUT_DURATION} for {spec.key} "
                f"(it takes the output length from the input video), "
                f"got {duration}"
            )
        return
    if spec.allowed_durations:
        if duration not in spec.allowed_durations:
            raise ValueError(
                f"duration must be one of {spec.allowed_durations} for "
                f"{spec.key}, got {duration}"
            )
        return
    if not (spec.min_duration_sec <= duration <= spec.max_duration_sec):
        raise ValueError(
            f"duration must be between {spec.min_duration_sec} and "
            f"{spec.max_duration_sec} inclusive for {spec.key}, got {duration}"
        )


def models_supporting_segment_len(seconds: float) -> list[str]:
    """Keys of every model that can generate a clip of *seconds* length."""
    return [k for k, s in AI_MODELS.items() if s.max_clip_sec + 0.05 >= seconds]


def models_excluded_by_segment_len(seconds: float) -> list[str]:
    """Keys of every model that CANNOT generate a clip of *seconds* length."""
    return [k for k, s in AI_MODELS.items() if s.max_clip_sec + 0.05 < seconds]


def resolution_choices_json() -> str:
    """JSON ``{model: [[value, label], ...]}`` for the New Run form's JS.

    Serialised once and injected into the template so the client-side
    resolution dropdown is rebuilt from this table rather than a hand-kept copy.
    """
    return json.dumps(
        {
            key: [[r, _RESOLUTION_LABELS.get(r, r)] for r in spec.resolutions]
            for key, spec in AI_MODELS.items()
        }
    )


def model_limits_json() -> str:
    """JSON ``{model: {max_clip_sec, produces_audio, label}}`` for the form's JS.

    Powers the client-side "these swap segments are too long for the selected
    model" warning and the audio-control locking, without hardcoding either
    model's limits in the template.
    """
    return json.dumps(
        {
            key: {
                "max_clip_sec": spec.max_clip_sec,
                "produces_audio": spec.produces_audio,
                "label": spec.label,
            }
            for key, spec in AI_MODELS.items()
        }
    )


# Resolution option labels, shared by the New Run form and the run-detail copy
# control so both describe a resolution the same way.
_RESOLUTION_LABELS = {
    "480p": "480p — cheapest, use for tests",
    "720p": "720p — balanced",
    "1080p": "1080p — production quality",
    "4k": "4k — maximum quality",
}
